### ISSUE TITLE
New added item did't come up in search result

### ISSUE THREAD

**Issue by tecxar-neel** [juicedio/Bug-reports#14]
The search page is not working.I added an item and it @didn't come up when i searched it

**Comment by iamsr** [comment]
As discussed earleir search takes a heavy load on our test servers and due to seller hub being running on that server we was turned off the elastic search module of our system. I am attaching a video in comment to show that search functionality works on item add. Once you test the same thing on your end let us know so that we can turn off the search module to make the room for other modules.  Thanks

Note : Newly added item will appear in search result after 1 Min.

https://user-images.githubusercontent.com/24357511/144179782-5feeb2b9-ced0-41ac-a876-f5e8e241a3e7.mp4

**Comment by tecxar-neel** [comment]
Okay
